#!/bin/bash

echo $0 $1 $2

# Check if exactly one argument is provided
if [ $# -ne 2 ] && [ "$1" != "compile" ]; then
  echo "Usage: $0 compile <path-to-monet-file>"
  exit 1
fi

# Define the environment variable
# env="default_path/"

# Concatenate the argument to the environment variable
# TARGET_FILE="${env}$2"

if [ $# -eq 2 ] && [ "$1" = "compile" ]; then
  # echo "Compiling " + $2 + "..."
  # Execute the command using the concatenated environment variable
  TARGET_FILE="$2" wasm-pack build --target web
fi


# Check if the command was successful
if [ $? -eq 0 ]; then
  echo "Compiled successfully."
  # echo "Compiled: $TARGET_FILE"
else
  echo "Compilation failed."
fi